### ISSUE TITLE
Search does not work for "Use visible area"

### ISSUE THREAD

**Issue by PelJon** [Kan-T-IT/QGIS-KICa#25]
**Describe the bug**
While searching through the UP42 catalog, the search does not return any results for the **Search area** with checkmark **Use visible area**

**To Reproduce**
1. Go to KAN imagery CATALOG v0.3
2. Enter credentials for UP42
3. Use Search area **Use visible area**
4. Use QuickMapServices Plug-In and get Basemap OSM standard
5. Zoom to Hamburg, Germany 
3. Select PNEO with Cloud Coverage below 50% for the last 6 months
6. Search

**Expected behavior**
Return results for PNEO for Hamburg for the last 6 months with cloud coverage below 50%

**Additional information**
The search loads, if you add at least one additional layer (e.g., TIF).

**Comment by fgomezdev** [comment]
Hi @PelJon, for the search it is necessary to have some active layer in the TOC, you could select the OSM basemap for example. Have you tried it?

**Comment by PelJon** [comment]
This is solved now!
