### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by dmassone** [Kan-T-IT/QGIS-KICa#6]
**Describe the bug**
the configuration tool does not appear

**To Reproduce**
1. Go to 'Complementos > Kan imagery Catalog'

**Expected behavior**
In the previous version the tool appeared in the left margin
**Screenshots**
![image](https://github.com/Kan-T-IT/QGIS-KICa/assets/86256858/3f5b8650-dd7f-4044-a8d7-af57fee8fe0b)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fgomezdev** [comment]
Hi, after a plugin update it is recommended to restart QGIS, as I see you are running an outdated version of the plugin.
