### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [Kan-T-IT/QGIS-KICa#7]
# Problem

Please update the plugin homepage. If you intend to use your website we need to have a dedicated page showing the plugin features otherwise just use the repo as the plugin homepage

**Comment by anthieni** [comment]
The change was made in the readme of the link to the documentation repository and in the metadata.

**Comment by NyakudyaA** [comment]
@anthieni Can you update the plugin in the qgis plugin repository. It still shows the old homepage url

**Comment by anthieni** [comment]
@NyakudyaA The new version is already uploaded https://plugins.qgis.org/plugins/kan_imagery_catalog/ sorry, this is the first time we upload a plugin. I don't know what the next steps are for approval. Thank you
